##fdfs
#soTimeout: 1500 #socket连接超时时长
#connectTimeout: 600 #连接tracker服务器超时时长
#resHost: 127.0.0.1
#storagePort: 8889
#thumbImage: #缩略图生成参数，可选
#  width: 150
#  height: 150
#trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
#  - 127.0.0.1:22122
#
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 127.0.0.1:22122

image:
  adress: http://127.0.0.1:8888/